"""FlowGraph IR: pydantic models plus stable YAML (de)serialisation."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Annotated, Any, Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field

FlowStatus = Literal["candidate", "shadow", "active", "retired"]
BindingSource = Literal["const", "slot", "output", "transform", "llm"]

# Reserved step targets.
END = "end"
FALLBACK = "fallback"


class _Model(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)


class Binding(_Model):
    source: BindingSource = Field(alias="from")
    value: Any = None  # const
    slot: str | None = None  # slot
    step: str | None = None  # output
    path: str | None = None  # output
    fn: str | None = None  # transform
    input: Binding | None = None  # transform
    hint: str | None = None  # llm: what the value is


class LearnedDomain(_Model):
    """Observed value domain. Values outside it at runtime trigger a fallback."""

    path: str  # namespace path, e.g. "output.found", "args.date", "slot.name"
    kind: Literal["enum", "range", "pattern", "not_null", "length", "member_of"]
    values: list[Any] | None = None  # enum values / shape patterns
    min: float | None = None
    max: float | None = None
    container: str | None = None  # member_of: namespace path of the containing list
    fn: str | None = None  # member_of: transform applied to the value first
    support: int = 0


class SlotDef(_Model):
    extractor: str
    description: str = ""


class Membership(_Model):
    residual_max_tokens: int = 3
    classifier: str | None = None
    accept_threshold: float | None = None
    reject_threshold: float | None = None
    calibration: dict[str, Any] | None = None


class LLMPhrase(_Model):
    intent: str
    inputs: list[str] = Field(default_factory=list)
    max_tokens: int = 60
    example: str = ""


class Say(_Model):
    template: str | None = None
    llm: LLMPhrase | None = None
    coverage: float | None = None  # share of traces the template explains


class ToolStep(_Model):
    id: str
    kind: Literal["tool"] = "tool"
    tool: str
    side_effect: Literal["read_only", "reversible", "irreversible"] = "irreversible"
    args: dict[str, Binding] = Field(default_factory=dict)
    guards: list[str] = Field(default_factory=list)
    learned_guards: list[LearnedDomain] = Field(default_factory=list)
    next: str = END


class AskStep(_Model):
    id: str
    kind: Literal["ask"] = "ask"
    expects: list[str] = Field(default_factory=list)
    say: Say
    guards: list[str] = Field(default_factory=list)
    learned_guards: list[LearnedDomain] = Field(default_factory=list)
    membership: Membership = Field(default_factory=Membership)
    next: str = END


class ConfirmStep(_Model):
    id: str
    kind: Literal["confirm"] = "confirm"
    say: Say
    on_yes: str
    on_no: str = FALLBACK
    inserted: bool = False  # generated by the compiler (not observed in traces)


class SayStep(_Model):
    id: str
    kind: Literal["say"] = "say"
    say: Say
    next: str = END


class LLMStep(_Model):
    """Explicit, typed LLM node. Never on an irreversible path's arguments."""

    id: str
    kind: Literal["llm"] = "llm"
    intent: str
    inputs: list[str] = Field(default_factory=list)
    max_tokens: int = 60
    next: str = END


class BranchCase(_Model):
    when: str
    next: str


class BranchStep(_Model):
    id: str
    kind: Literal["branch"] = "branch"
    cases: list[BranchCase]
    default: str = FALLBACK


class EndStep(_Model):
    id: str
    kind: Literal["end"] = "end"


Step = Annotated[
    ToolStep | AskStep | ConfirmStep | SayStep | LLMStep | BranchStep | EndStep,
    Field(discriminator="kind"),
]


class Entry(_Model):
    slots: list[str] = Field(default_factory=list)
    description: str = ""
    guards: list[str] = Field(default_factory=list)
    learned_guards: list[LearnedDomain] = Field(default_factory=list)


class BindingProvenance(_Model):
    source: BindingSource = Field(alias="class")
    support: int


class Provenance(_Model):
    support: int = 0
    sessions: list[str] = Field(default_factory=list)
    tool_signature: list[str] = Field(default_factory=list)
    shape: list[list[str]] = Field(default_factory=list)
    bindings: dict[str, BindingProvenance] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)


class FlowGraph(_Model):
    flow_id: str
    version: int = 1
    status: FlowStatus = "candidate"
    description: str = ""
    entry: Entry = Field(default_factory=Entry)
    slots: dict[str, SlotDef] = Field(default_factory=dict)
    steps: list[Step]
    provenance: Provenance = Field(default_factory=Provenance)
    content_hash: str | None = None

    def step(self, step_id: str) -> Step:
        for s in self.steps:
            if s.id == step_id:
                return s
        raise KeyError(step_id)

    def has_step(self, step_id: str) -> bool:
        return any(s.id == step_id for s in self.steps)

    @property
    def first_step(self) -> str:
        return self.steps[0].id

    def successors(self, step_id: str) -> list[str]:
        s = self.step(step_id)
        if isinstance(s, ConfirmStep):
            return [s.on_yes, s.on_no]
        if isinstance(s, BranchStep):
            return [c.next for c in s.cases] + [s.default]
        if isinstance(s, EndStep):
            return []
        return [s.next]

    def compute_hash(self) -> str:
        body = self.model_dump(
            mode="json", by_alias=True, exclude={"status", "version", "content_hash"}
        )
        canon = json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        return "sha256:" + hashlib.sha256(canon.encode()).hexdigest()


def _clean(obj: Any) -> Any:
    """Drop None values and empty containers for compact, stable YAML."""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            v = _clean(v)
            if v is None or v == [] or v == {}:
                continue
            out[k] = v
        return out
    if isinstance(obj, list):
        return [_clean(v) for v in obj]
    return obj


# libyaml's C implementation when available: much faster, so YAML work on an
# executor thread holds the GIL (and delays the audio loop) for far less time.
_BaseDumper = getattr(yaml, "CSafeDumper", yaml.SafeDumper)
_Loader = getattr(yaml, "CSafeLoader", yaml.SafeLoader)


class _Dumper(_BaseDumper):  # type: ignore[misc,valid-type]
    pass


def _repr_str(dumper: yaml.SafeDumper, data: str) -> yaml.ScalarNode:
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(str, _repr_str)


def dump_flow(flow: FlowGraph) -> str:
    data = _clean(flow.model_dump(mode="json", by_alias=True))
    return yaml.dump(
        data,
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=None,
        width=10_000,
    )


def load_flow(path: str | Path) -> FlowGraph:
    with open(path, encoding="utf-8") as fh:
        return parse_flow(fh.read())


def parse_flow(text: str) -> FlowGraph:
    return FlowGraph.model_validate(yaml.load(text, Loader=_Loader))


def save_flow(flow: FlowGraph, path: str | Path) -> None:
    Path(path).write_text(dump_flow(flow), encoding="utf-8")
